server:
  port: 3355

spring:
  main:
    banner-mode: off
  config:
    import: "optional:configserver:"
  application:
    name: cloud-config-client-3355
  cloud:
    #Config客户端配置
    config:
      discovery:
        enabled: true
        serviceId: CLOUD-CONFIG-CENTER
      fail-fast: true # if can not connect, stop immediately
      enabled: true
      label: master #分支名称
      name: app1
      uri:
        - http://CLOUD-CONFIG-CENTER
      profile: dev1 #读取后缀名称   上述3个综合：master分支上config-dev.yml的配置文件被读取http://config-3344.com:3344/master/config-dev.yml

  # Since profile is not config here, so it will direct read cloud-config-client-3355.yml from different branch



  ########################################################################################################
  #rabbitmq相关配置 15672是Web管理界面的端口；5672是MQ访问的端口
  # this is [spring.rabbitmq]
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
########################################################################################################




#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

