server:
  port: 3344

spring:
  main:
    banner-mode: off
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      label: master
      server:
        git:
          refreshRate: 10
          default-label: master
          uri: https://github.com/632691987/config-server-demo.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - config-server-demo

#################################################################################################
#rabbitmq相关配置
  # this is [spring.rabbitmq]
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'busrefresh'
#################################################################################################




#服务注册到eureka地址
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

