server:
  port: 7002

spring:
  main:
    banner-mode: off

eureka:
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: false # No need to register himself
    fetch-registry: false # No need to check myself service
    service-url:
      #集群指向其它eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
      #单机就是7001自己
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    #server:
    #关闭自我保护机制，保证不可用服务被及时踢除
    #enable-self-preservation: false
    #eviction-interval-timer-in-ms: 2000