server:
  port: 9002

application:
  payment-service-url: http://CLOUD-PAYMENT-SERVICE

spring:
  application:
    name: cloud-consumer-order
  cloud:
    #注册到zookeeper地址
    zookeeper:
      connect-string: localhost:2181